stages:
  - test

variables:
  APP_ENV: ai_env

run_tests:
  image: python:3.11  # use latest stable python version
  stage: test
  script:
    - echo "Running tests"
    - sudo apt update
    - sudo apt install -y libgl1
    - python -m venv $APP_ENV        # Create virtual environment
    - source $APP_ENV/bin/activate   # Activate environment
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - chmod +x run_tests.py
    - ./run_tests.py
    - deactivate
